---
  team_mappings:
    Customer Success: 100
    Human Resources: 90
    Value Added Services: 85
    Value Added Services - Acct Mgmt: 80
    Sales: 70
    Marketing: 60
    Finance: 50
    Client Services: 40
    Implementation: 30
    Product Management: 20
    Software Engineering: 10
    Software Engineering - Web Ops: 0
  floor_mappings:
    Customer Success: 0
    Human Resources: 100
    Value Added Services: 100
    Value Added Services - Acct Mgmt: 100
    Sales: 100
    Marketing: 100
    Finance: 100
    Client Services: 0
    Implementation: 0
    Product Management: 0
    Software Engineering: 0
    Software Engineering - Web Ops: 0
  weights:
    floor: 0.4
    days_here: 0.2
    team: 0.9
  min_lunch_group_size: 4
